# Setup
title:               Nippun Sharma
tagline:             'Do what you love'
description:         'A personal website about things that I find useful.'
url:                 https://nippunsharma.github.io
baseurl:             https://nippunsharma.github.io
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Nippun Sharma

contact:
  github:            https://github.com/NippunSharma
  email:             inbox.nippun@gmail.com
  linkedin:          https://linkedin.com/in/nippun-sharma

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
