# Setup
title:               Nippun Sharma
tagline:             ''
description:         ''
url:                 https://nippunsharma.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Nippun Sharma

contact:
  github:            https://github.com/NippunSharma
  email:             inbox.nippun@gmail.com
  linkedin:          https://linkedin.com/in/nippun-sharma

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
